spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/labo_final
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp-mail.outlook.com
    port: 587
    username: quizzy-no-reply@outlook.com
    password: QuizzySecret2x
    properties:
      mail:
        protocol: smtp
        tls:
          true
        smtp:
          auth: true
          starttls:
            enable:
              true
          ssl:
            trust:
              smtp-mail.outlook.com:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  springdoc:
    swagger-ui:
      path: /swagger
